apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 
  name: jmeter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: jmeter
    spec:
      containers:
      - image: mimi50/jmeter
        name: jmeter
        command:
        - "java"
        args:
        - "-jar"
        - "/opt/jmeter/slave.jar"
        - "-jnlpUrl"
        - "http://jenkins:8080/computer/jmeter/slave-agent.jnlp"
        - "-secret"
        - "70700fd2dee6f646297fe299475b8dbe13b052c0149f04d757d23bacf286036c"
        resources: {}
        volumeMounts:
        - mountPath: "/tmp/jmeter"
          name: jmeter-claim0
      restartPolicy: Always
      volumes:
      - name: jmeter-claim0
        persistentVolumeClaim:
          claimName: jmeter-claim0
status: {}
