kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0003
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hosthome/eisraily/jmx"
